spring.application.name=pos-ai

spring.datasource.url=jdbc:postgresql://localhost:5432/project_bd
spring.datasource.username=romax-admin
spring.datasource.password=f4ast3rv3rs10n*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/test?retryWrites=true&loadBalanced=false&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
imgbb.api.key=f9a44f0bfd88b742972d77e044326a0e
deepl.api.key=9c75ce66-35ab-47cf-a2e0-6361cd86f1ae:fx
